version: '3.9'

services:
  postgres:
    image: postgres
    container_name: vollmed_api
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=vollmed_api